"""se añadió el slug al modelo de post

Revision ID: 269736797e7e
Revises: a64ede2637f2
Create Date: 2024-07-03 10:36:30.427109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269736797e7e'
down_revision = 'a64ede2637f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
